<?php

return [
            [
                'name' => 'RSB Berkane',
                'short_name' => 'RSB',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/316652.png',
                'city' => 'Berkane',
                'players' => [
                    [
                        'first_name' => 'Munir',
                        'last_name' => '',
                        'birth_date' => '1989-05-10',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/573787.png',
                    ],
                    [
                        'first_name' => 'Amine',
                        'last_name' => 'El Maswab',
                        'birth_date' => '2000-08-08',
                        'position' => 'CB',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687520.png',
                    ],
                    [
                        'first_name' => 'Soumaila',
                        'last_name' => 'Sidibe',
                        'birth_date' => '1997-12-11',
                        'position' => 'CM',
                        'number' => 5,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1529986.png',
                    ],
                    [
                        'first_name' => 'Oussama',
                        'last_name' => 'Lamlioui',
                        'birth_date' => '1996-01-02',
                        'position' => 'ST',
                        'number' => 9,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1238150.png',
                    ],
                    [
                        'first_name' => 'Mehdi',
                        'last_name' => 'Maftah',
                        'birth_date' => '1993-08-10',
                        'position' => 'GK',
                        'number' => 12,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1520018.png',
                    ],
                ],
            ],
            [
                'name' => 'MAS Fes',
                'short_name' => 'MAS',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102043.png',
                'city' => 'Fes',
                'players' => [
                    [
                        'first_name' => 'Walid',
                        'last_name' => 'Laghrissi',
                        'birth_date' => '2008-11-08',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810613.png',
                    ],
                    [
                        'first_name' => 'Hamza',
                        'last_name' => 'Ait Allal',
                        'birth_date' => '2000-01-08',
                        'position' => 'RB',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1688441.png',
                    ],
                    [
                        'first_name' => 'Hamza',
                        'last_name' => 'Oukaili',
                        'birth_date' => '2001-10-21',
                        'position' => 'MID',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687596.png',
                    ],
                    [
                        'first_name' => 'Kabelo',
                        'last_name' => 'Seakanyeng',
                        'birth_date' => '1993-06-25',
                        'position' => 'LW',
                        'number' => 7,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/580840.png',
                    ],
                    [
                        'first_name' => 'Oussama',
                        'last_name' => 'Errahmany',
                        'birth_date' => '2003-04-21',
                        'position' => 'GK',
                        'number' => 12,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687490.png',
                    ],
                ],
            ],
            [
                'name' => 'CODM Meknes',
                'short_name' => 'COD',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102032.png',
                'city' => 'Meknes',
                'players' => [
                    [
                        'first_name' => 'Aymane',
                        'last_name' => 'Majid',
                        'birth_date' => '1995-01-04',
                        'position' => 'GK',
                        'number' => 13,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687582.png',
                    ],
                    [
                        'first_name' => 'Ayoub',
                        'last_name' => 'Lourhraz',
                        'birth_date' => '2001-02-17',
                        'position' => 'DEF',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687436.png',
                    ],
                    [
                        'first_name' => 'Adnane',
                        'last_name' => 'Berdad',
                        'birth_date' => '1993-08-25',
                        'position' => 'CDM',
                        'number' => 6,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1682407.png',
                    ],
                    [
                        'first_name' => 'Mohamed',
                        'last_name' => 'Ferhane',
                        'birth_date' => '2003-09-05',
                        'position' => 'ATT',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1800033.png',
                    ],
                    [
                        'first_name' => 'Reda',
                        'last_name' => 'Bounaga',
                        'birth_date' => '1989-01-01',
                        'position' => 'GK',
                        'number' => 34,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687407.png',
                    ],
                ],
            ],
            [
                'name' => 'FAR Rabat',
                'short_name' => 'FAR',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102035.png',
                'city' => 'Rabat',
                'players' => [
                    [
                        'first_name' => 'Ayoub',
                        'last_name' => 'El Khayati',
                        'birth_date' => '1998-01-31',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687413.png',
                    ],
                    [
                        'first_name' => 'To',
                        'last_name' => 'Carneiro',
                        'birth_date' => '1995-11-05',
                        'position' => 'LB',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/931052.png',
                    ],
                    [
                        'first_name' => 'Taoufik',
                        'last_name' => 'Razko',
                        'birth_date' => '2002-01-01',
                        'position' => 'CAM',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1681982.png',
                    ],
                    [
                        'first_name' => 'Youssef',
                        'last_name' => 'El Fahli',
                        'birth_date' => '1997-04-27',
                        'position' => 'ST',
                        'number' => 7,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1033307.png',
                    ],
                    [
                        'first_name' => 'Ahmed',
                        'last_name' => 'Tagnaouti',
                        'birth_date' => '1996-04-05',
                        'position' => 'GK',
                        'number' => 16,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/885288.png',
                    ],
                ],
            ],
            [
                'name' => 'Raja Casablanca',
                'short_name' => 'RCA',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102049.png',
                'city' => 'Casablanca',
                'players' => [
                    [
                        'first_name' => 'El',
                        'last_name' => 'Mehdi Al Harrar',
                        'birth_date' => '2000-11-30',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687452.png',
                    ],
                    [
                        'first_name' => 'Ismail',
                        'last_name' => 'Mokadem',
                        'birth_date' => '1995-07-26',
                        'position' => 'CB',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1033124.png',
                    ],
                    [
                        'first_name' => 'Hilal',
                        'last_name' => 'Ferdaoussi',
                        'birth_date' => '1999-06-23',
                        'position' => 'CDM',
                        'number' => 8,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1557079.png',
                    ],
                    [
                        'first_name' => 'Victor',
                        'last_name' => 'Abrego',
                        'birth_date' => '1997-02-11',
                        'position' => 'ST',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/929216.png',
                    ],
                    [
                        'first_name' => 'Khalid',
                        'last_name' => 'Alaoui',
                        'birth_date' => '1996-06-28',
                        'position' => 'GK',
                        'number' => 12,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1214369.png',
                    ],
                ],
            ],
            [
                'name' => 'Wydad Casablanca',
                'short_name' => 'WC',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102050.png',
                'city' => 'Casablanca',
                'players' => [
                    [
                        'first_name' => 'Abdelali',
                        'last_name' => 'M\'Hamdi',
                        'birth_date' => '1991-11-29',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/627100.png',
                    ],
                    [
                        'first_name' => 'Mohamed',
                        'last_name' => 'Moufid',
                        'birth_date' => '2000-01-12',
                        'position' => 'RB',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687433.png',
                    ],
                    [
                        'first_name' => 'Hamza',
                        'last_name' => 'Sakhi',
                        'birth_date' => '1996-06-07',
                        'position' => 'CAM',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/491901.png',
                    ],
                    [
                        'first_name' => 'Hamza',
                        'last_name' => 'El Wasti',
                        'birth_date' => '1995-01-01',
                        'position' => 'ST',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/760308.png',
                    ],
                    [
                        'first_name' => 'Youssef',
                        'last_name' => 'El Motie',
                        'birth_date' => '1994-12-16',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1435081.png',
                    ],
                ],
            ],
            [
                'name' => 'Union Touarga Sport',
                'short_name' => 'UTS',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/320835.png',
                'city' => 'Rabat',
                'players' => [
                    [
                        'first_name' => 'Houssam',
                        'last_name' => 'Bouelainine',
                        'birth_date' => '2004-10-13',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810756.png',
                    ],
                    [
                        'first_name' => 'Ismail',
                        'last_name' => 'Al Alami',
                        'birth_date' => '2000-01-01',
                        'position' => 'DEF',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1415490.png',
                    ],
                    [
                        'first_name' => 'Abdellah',
                        'last_name' => 'Boudlal',
                        'birth_date' => null,
                        'position' => 'MID',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1752371.png',
                    ],
                    [
                        'first_name' => 'Abdelkabir',
                        'last_name' => 'El Ouadi',
                        'birth_date' => '1993-02-20',
                        'position' => 'LW',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/844170.png',
                    ],
                    [
                        'first_name' => 'Walid',
                        'last_name' => 'Hasbi',
                        'birth_date' => '2004-07-01',
                        'position' => 'GK',
                        'number' => 5,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810752.png',
                    ],
                ],
            ],
            [
                'name' => 'Ittihad Tanger',
                'short_name' => 'IT',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/316657.png',
                'city' => 'Tanger',
                'players' => [
                    [
                        'first_name' => 'Malcolm',
                        'last_name' => 'Barcola',
                        'birth_date' => '1999-05-14',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/970146.png',
                    ],
                    [
                        'first_name' => 'Mohamed',
                        'last_name' => 'Saoud',
                        'birth_date' => '1996-01-30',
                        'position' => 'RB',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1403643.png',
                    ],
                    [
                        'first_name' => 'Mohsine',
                        'last_name' => 'Moutouali',
                        'birth_date' => '1986-03-03',
                        'position' => 'CAM',
                        'number' => 5,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/193961.png',
                    ],
                    [
                        'first_name' => 'Papa',
                        'last_name' => 'Magueye Gaye',
                        'birth_date' => '2006-05-15',
                        'position' => 'ATT',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810375.png',
                    ],
                    [
                        'first_name' => 'Amine',
                        'last_name' => 'El Ouaad',
                        'birth_date' => '1995-12-08',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1707916.png',
                    ],
                ],
            ],
            [
                'name' => 'Olympic Club de Safi',
                'short_name' => 'OCD',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102047.png',
                'city' => 'Safi',
                'players' => [
                    [
                        'first_name' => 'Abderrahmane',
                        'last_name' => 'Kernane',
                        'birth_date' => '2000-02-24',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687384.png',
                    ],
                    [
                        'first_name' => 'Aboubacar',
                        'last_name' => 'Sylla',
                        'birth_date' => '2003-12-31',
                        'position' => 'DEF',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810624.png',
                    ],
                    [
                        'first_name' => 'Ahmed',
                        'last_name' => 'El Houari',
                        'birth_date' => '2004-02-17',
                        'position' => 'CAM',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687478.png',
                    ],
                    [
                        'first_name' => 'Anas',
                        'last_name' => 'Samoudi',
                        'birth_date' => '2007-06-25',
                        'position' => 'ST',
                        'number' => 7,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687392.png',
                    ],
                    [
                        'first_name' => 'Imad',
                        'last_name' => 'Askar',
                        'birth_date' => '1998-05-29',
                        'position' => 'GK',
                        'number' => 12,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1800329.png',
                    ],
                ],
            ],
            [
                'name' => 'Difaa El Jadida',
                'short_name' => 'DEJ',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102033.png',
                'city' => 'El Jadida',
                'players' => [
                    [
                        'first_name' => 'Haytam',
                        'last_name' => 'Bentounsi',
                        'birth_date' => '2003-01-01',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810276.png',
                    ],
                    [
                        'first_name' => 'Oussama',
                        'last_name' => 'Benchchaoui',
                        'birth_date' => '2001-01-01',
                        'position' => 'RB',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687467.png',
                    ],
                    [
                        'first_name' => 'Youssef',
                        'last_name' => 'El Ghazoui',
                        'birth_date' => '2000-10-25',
                        'position' => 'CM',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1657703.png',
                    ],
                    [
                        'first_name' => 'Imad',
                        'last_name' => 'Sabik',
                        'birth_date' => '1997-06-05',
                        'position' => 'ATT',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810263.png',
                    ],
                    [
                        'first_name' => 'Marouane',
                        'last_name' => 'Bessak',
                        'birth_date' => '1996-08-14',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687397.png',
                    ],
                ],
            ],
            [
                'name' => 'Hassania Agadir',
                'short_name' => 'HA',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102037.png',
                'city' => 'Agadir',
                'players' => [
                    [
                        'first_name' => 'Ilyass',
                        'last_name' => 'Motik',
                        'birth_date' => '2004-08-01',
                        'position' => 'GK',
                        'number' => 31,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687587.png',
                    ],
                    [
                        'first_name' => 'Adil',
                        'last_name' => 'Garnan',
                        'birth_date' => '2004-07-10',
                        'position' => 'DEF',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810326.png',
                    ],
                    [
                        'first_name' => 'Ayoub',
                        'last_name' => 'Yousfi',
                        'birth_date' => '2002-12-30',
                        'position' => 'MID',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1284736.png',
                    ],
                    [
                        'first_name' => 'Mohamed',
                        'last_name' => 'Bakhkhach',
                        'birth_date' => '2002-01-01',
                        'position' => 'LW',
                        'number' => 7,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1531927.png',
                    ],
                    [
                        'first_name' => 'Badreddine',
                        'last_name' => 'Abyir',
                        'birth_date' => '1998-08-27',
                        'position' => 'GK',
                        'number' => 61,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687379.png',
                    ],
                ],
            ],
            [
                'name' => 'Union Yacoub El-Mansour',
                'short_name' => 'UYE',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/1786714.png',
                'city' => 'Rabat',
                'players' => [
                    [
                        'first_name' => 'Hafs',
                        'last_name' => 'Kasbi',
                        'birth_date' => '2002-03-20',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810762.png',
                    ],
                    [
                        'first_name' => 'Mohamed',
                        'last_name' => 'Nasser Allah Jamal',
                        'birth_date' => '1997-04-28',
                        'position' => 'DEF',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810765.png',
                    ],
                    [
                        'first_name' => 'Ilyass',
                        'last_name' => 'Badri',
                        'birth_date' => '1998-02-02',
                        'position' => 'MID',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810764.png',
                    ],
                    [
                        'first_name' => 'Ilyas',
                        'last_name' => 'Bougafer',
                        'birth_date' => '2003-01-28',
                        'position' => 'ATT',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1243244.png',
                    ],
                    [
                        'first_name' => 'Hassan',
                        'last_name' => 'Doughmi',
                        'birth_date' => '2000-05-10',
                        'position' => 'GK',
                        'number' => 64,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687471.png',
                    ],
                ],
            ],
            [
                'name' => 'Renaissance Club Zemamra',
                'short_name' => 'RCZ',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/950070.png',
                'city' => 'Zemamra',
                'players' => [
                    [
                        'first_name' => 'Aissa',
                        'last_name' => 'Sioudi',
                        'birth_date' => '1997-09-20',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/953332.png',
                    ],
                    [
                        'first_name' => 'Yahya',
                        'last_name' => 'Jammali',
                        'birth_date' => '2001-03-14',
                        'position' => 'DEF',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687530.png',
                    ],
                    [
                        'first_name' => 'Anass',
                        'last_name' => 'El Ghannouj',
                        'birth_date' => '1997-01-06',
                        'position' => 'MID',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1754712.png',
                    ],
                    [
                        'first_name' => 'Ahmed',
                        'last_name' => 'Rhailouf',
                        'birth_date' => '2004-08-30',
                        'position' => 'ST',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687457.png',
                    ],
                    [
                        'first_name' => 'Mohamed',
                        'last_name' => 'Ferni',
                        'birth_date' => '1999-12-01',
                        'position' => 'GK',
                        'number' => 22,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687408.png',
                    ],
                ],
            ],
            [
                'name' => 'KACM',
                'short_name' => 'KAC',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102042.png',
                'city' => 'Marrakech',
                'players' => [
                    [
                        'first_name' => 'Anass',
                        'last_name' => 'Rachak',
                        'birth_date' => '2007-04-29',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810388.png',
                    ],
                    [
                        'first_name' => 'Ismail',
                        'last_name' => 'Gazaoui',
                        'birth_date' => '1998-05-07',
                        'position' => 'DEF',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810405.png',
                    ],
                    [
                        'first_name' => 'Ousseini',
                        'last_name' => 'Badamassi',
                        'birth_date' => '1997-04-21',
                        'position' => 'CM',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1435384.png',
                    ],
                    [
                        'first_name' => 'Hamza',
                        'last_name' => 'Founti',
                        'birth_date' => '2000-02-17',
                        'position' => 'ATT',
                        'number' => 7,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810427.png',
                    ],
                    [
                        'first_name' => 'Mohamed',
                        'last_name' => 'Baayou',
                        'birth_date' => '1993-01-11',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810387.png',
                    ],
                ],
            ],
            [
                'name' => 'FUS Rabat',
                'short_name' => 'FUS',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/102036.png',
                'city' => 'Rabat',
                'players' => [
                    [
                        'first_name' => 'Ayoub',
                        'last_name' => 'Lakred',
                        'birth_date' => '1995-06-21',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1213529.png',
                    ],
                    [
                        'first_name' => 'Yassine',
                        'last_name' => 'Amhih',
                        'birth_date' => '2003-02-18',
                        'position' => 'CB',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1687422.png',
                    ],
                    [
                        'first_name' => 'Anas',
                        'last_name' => 'Serrhat',
                        'birth_date' => '1996-11-01',
                        'position' => 'CDM',
                        'number' => 5,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1243577.png',
                    ],
                    [
                        'first_name' => 'Chouaib',
                        'last_name' => 'Faidi',
                        'birth_date' => '1999-09-10',
                        'position' => 'LW',
                        'number' => 7,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1411843.png',
                    ],
                    [
                        'first_name' => 'Rachid',
                        'last_name' => 'Ghanimi',
                        'birth_date' => '2001-04-25',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1499520.png',
                    ],
                ],
            ],
            [
                'name' => 'Olympique Dcheira',
                'short_name' => 'OD',
                'logo_path' => 'https://images.fotmob.com/image_resources/logo/teamlogo/570487.png',
                'city' => 'Agadir',
                'players' => [
                    [
                        'first_name' => 'Mohamed',
                        'last_name' => 'Idar',
                        'birth_date' => '1986-01-24',
                        'position' => 'GK',
                        'number' => 1,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1762870.png',
                    ],
                    [
                        'first_name' => 'Younes',
                        'last_name' => 'El Khafi',
                        'birth_date' => '1994-04-11',
                        'position' => 'DEF',
                        'number' => 2,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810645.png',
                    ],
                    [
                        'first_name' => 'Charaf-Eddine',
                        'last_name' => 'Boulahroud',
                        'birth_date' => '2001-02-21',
                        'position' => 'MID',
                        'number' => 3,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1577964.png',
                    ],
                    [
                        'first_name' => 'Yassine',
                        'last_name' => 'Jabrane',
                        'birth_date' => '2000-05-15',
                        'position' => 'ATT',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810640.png',
                    ],
                    [
                        'first_name' => 'Ismail',
                        'last_name' => 'Soubai',
                        'birth_date' => '2000-01-10',
                        'position' => 'RB',
                        'number' => 4,
                        'photo_path' => 'https://images.fotmob.com/image_resources/playerimages/1810646.png',
                    ],
                ],
            ],
]; 
